In [1]:
import pandas as pd

In [20]:
dfgold = pd.read_parquet('../../data/cell/cell_papers_selected_novelty.parquet')
print(dfgold.columns)
selected_columns = [
    'pubmed_id',
    'openalex',
    'novelty_sum',
    'top5_novel',
    'top10_novel',
    'wangs_novelty',
    'dindex',
    'forward_citations_openalex'
]
dfgold = dfgold[selected_columns]

Index(['pubmed_id', 'forward_citations', 'novelty_sum', 'top5_novel',
       'top10_novel', 'wangs_novelty', 'fast_text_lof', 'title', 'keywords',
       'abstract', 'year', 'authors', 'openalex', 'doi',
       'forward_citations_openalex', 'dindex'],
      dtype='str')

In [21]:
dfgold

,pubmed_id,openalex,novelty_sum,top5_novel,top10_novel,wangs_novelty,dindex,forward_citations_openalex
8795,11779465,W1965843055,1.0,False,False,NaN,-0.009080,711.0
8796,11779463,W2046221312,1.0,False,False,NaN,-0.004666,303.0
8797,11779461,W2150589615,8.0,True,True,NaN,-0.010714,820.0
8798,11779460,W2087575288,1.0,False,False,NaN,-0.007171,305.0
8799,11779462,W1989011389,0.0,False,False,NaN,-0.051230,1142.0
...,...,...,...,...,...,...,...,...
15560,33333024,W3111836713,2.0,False,False,6.506138,-0.003039,424.0
15561,33232691,W3104955345,1.0,False,False,9.484737,-0.000770,275.0
15562,33278357,W3105908160,2.0,False,False,46.690230,-0.001123,1411.0
15563,33147445,W3093900830,1.0,False,False,8.542442,-0.000906,596.0
15564,33147444,W3094597057,2.0,False,False,17.319004,-0.000586,543.0

In [22]:
dforig = pd.read_csv("../../data/cell/papers_all_tags.csv")
selected_columns_orig = [
    'PUBMED ID',
    'NEW_FINDING',
    'originality'
] 
dforig = dforig[selected_columns_orig]
dforig = dforig.rename(columns={
    'PUBMED ID': 'pubmed_id',
    'NEW_FINDING': 'new_finding',
    'originality': 'originality'
})      
dforig['pubmed_id'] = dforig['pubmed_id'].astype(str)

In [23]:
dfgold.info()
dforig.info()

<class 'pandas.DataFrame'>
Index: 6770 entries, 8795 to 15564
Data columns (total 8 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   pubmed_id                   6770 non-null   str
 1   openalex                    6616 non-null   str
 2   novelty_sum                 6770 non-null   float64
 3   top5_novel                  6770 non-null   bool
 4   top10_novel                 6770 non-null   bool
 5   wangs_novelty               4106 non-null   float64
 6   dindex                      6482 non-null   float64
 7   forward_citations_openalex  6616 non-null   float64
dtypes: bool(2), float64(4), str(2)
memory usage: 508.2 KB
<class 'pandas.DataFrame'>
RangeIndex: 15653 entries, 0 to 15652
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   pubmed_id    15653 non-null  str
 1   new_finding  15653 non-null  float64
 2   originality  15653 non-null  float64
dtypes: float64(2), str(1)
memory usage: 479.5 KB

In [24]:
all_data = pd.merge(dfgold, dforig, on='pubmed_id', how='inner')
all_data

,pubmed_id,openalex,novelty_sum,top5_novel,top10_novel,wangs_novelty,dindex,forward_citations_openalex,new_finding,originality
0,11779465,W1965843055,1.0,False,False,NaN,-0.009080,711.0,1.0,0.855799
1,11779463,W2046221312,1.0,False,False,NaN,-0.004666,303.0,0.0,0.805782
2,11779461,W2150589615,8.0,True,True,NaN,-0.010714,820.0,7.0,0.890620
3,11779460,W2087575288,1.0,False,False,NaN,-0.007171,305.0,1.0,0.902148
4,11779462,W1989011389,0.0,False,False,NaN,-0.051230,1142.0,0.0,0.816867
...,...,...,...,...,...,...,...,...,...,...
6765,33333024,W3111836713,2.0,False,False,6.506138,-0.003039,424.0,1.0,0.883228
6766,33232691,W3104955345,1.0,False,False,9.484737,-0.000770,275.0,1.0,0.908626
6767,33278357,W3105908160,2.0,False,False,46.690230,-0.001123,1411.0,1.0,0.912680
6768,33147445,W3093900830,1.0,False,False,8.542442,-0.000906,596.0,1.0,0.896193
6769,33147444,W3094597057,2.0,False,False,17.319004,-0.000586,543.0,1.0,0.920489

In [25]:
all_data.to_parquet('../../data/cell/cell_papers_all_novelty_scores.parquet', index=False)